version: '3.4'

services:
  password-service:
    build: 
      context: .
      args: 
        PASSWD: /etc/passwd
        GROUP: /etc/group
    volumes:
      - .:/usr/src/app
      - ./test:/usr/src/app/test
    ports:
      - 8080:80
